### ISSUE TITLE
Update Rails

### ISSUE THREAD

**Issue by PragTob** [hacketyhack/hackety-hack.com#155]
First of all we probably should upgrade to rails 3.1.12 as this is an important security fix. 

Then we should also make an effort to go to Rails 4.0 as fast as possible. Dunno if all the gems we use are ready for that yet/if we need some major upgrade with them.

Maybe also 3.2.14 is ok as an intermediate version.

**Comment by dehvmartins** [comment]
Hi, do you still have plans to upgrade rails version? Rails 5 will be released and the project still using rails 3. I'd love to help in this issue.

**Comment by steveklabnik** [comment]
I am not maintaining Hackety Hack at all anymore :(
